import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.requiredHeight
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.KeyboardArrowLeft
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.ColorFilter
import androidx.compose.ui.res.colorResource
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.shayriapp.Model.ShayriAppModel

@Composable
fun MainToolBar(title : String , onClick : () -> Unit) {

    Box(
        modifier = Modifier
//            .fillMaxSize()
            .background(_root_ide_package_.androidx.compose.ui.graphics.Color(0xFF140B2E))
    ){
        Row (
            modifier = Modifier
                .fillMaxWidth()
                .padding(30.dp),
            verticalAlignment = Alignment.CenterVertically
        ){
            Card (modifier = Modifier.size(45.dp).clickable{
                onClick.invoke()
            },
                shape = CircleShape,
                colors = CardDefaults.cardColors(_root_ide_package_.androidx.compose.ui.graphics.Color(0xFF7D64FD))

            ){

                Box(modifier = Modifier.fillMaxSize()) {  Image(
                    imageVector = Icons.Default.KeyboardArrowLeft,
                    contentDescription = null,
                    modifier = Modifier
                        .size(70.dp, 80.dp)
                        .requiredHeight(60.dp),
                    colorFilter = ColorFilter.tint(_root_ide_package_.androidx.compose.ui.graphics.Color(0xFFFFFFFF)) // Use colorFilter instead of tint
                ) }



            }
            Spacer(modifier = Modifier.width(20.dp))
            Card(
                shape = RoundedCornerShape(150.dp),
                colors = CardDefaults.cardColors(_root_ide_package_.androidx.compose.ui.graphics.Color(0xFF372372))
            ) {
                Box (){ Text(title, fontWeight = FontWeight.W800,
                    color = colorResource(com.example.shayriapp.R.color.white),
                    fontSize = 22.sp,
                    modifier = Modifier.padding(24.dp),
                    fontStyle = FontStyle.Italic

                ) }


            }





        }



    }

}

@Preview(showBackground = true, showSystemUi = true)
@Composable
fun MainToolBarPrev() {
    MainToolBar("demo",{})

}

fun getlist(): List<ShayriAppModel>{
    return listOf<ShayriAppModel>(
        ShayriAppModel("Love", listOf(
            "My heart beats only for you.",
            "Love is not finding someone to live with, it's finding someone you can't live without.",
            "Your smile is the key to my happiness.",
            "Every moment with you is a beautiful dream come true.",
            "I never knew love until I met you.",
            "You are the reason I believe in love.",
            "With you, every day is Valentine’s Day.",
            "I found my paradise in your eyes.",
            "You complete me in every way.",
            "Forever is not enough when I’m with you.",
            "In your arms, I found my home.",
            "I want to grow old with you.",
            "Your love is my favorite melody.",
            "I love you more than words can say.",
            "You are the sunshine in my cloudy days.",
            "Loving you is like breathing, I can’t stop.",
            "You make my world brighter.",
            "Every heartbeat whispers your name.",
            "You’re not my number one; you’re my only one.",
            "You're the answer to all my prayers.",
            "I fall in love with you more every day.",
            "You're my today and all of my tomorrows.",
            "You're my once in a lifetime.",
            "Love brought us together, and fate sealed us forever.",
            "You're the reason behind my smile.",
            "Without you, my life is incomplete.",
            "My soul recognized yours the moment we met.",
            "You're my dream that came true.",
            "In your love, I found myself.",
            "You make my life a fairytale.",
            "Your love is my greatest strength.",
            "You’re the poem my heart wants to write.",
            "You're the reason I believe in forever.",
            "I feel lucky just to love you.",
            "With you, I’ve found endless peace.",
            "You are my heartbeat, my lifeline.",
            "You're the spark to my flame.",
            "You turned my life into a love story.",
            "You’re the magic in my world.",
            "I cherish every moment spent with you.",
            "Our love story is my favorite.",
            "With you, time stands still.",
            "Your love makes me whole.",
            "I wish I could pause time with you.",
            "You stole my heart, and I don’t want it back.",
            "You're my forever and always.",
            "Even forever isn’t long enough with you.",
            "In your smile, I see my future.",
            "You're my greatest adventure.",
            "Love is you and me, endlessly.",
            "तेरी मुस्कान मेरी सबसे बड़ी खुशी है।",
            "तेरा साथ हो तो हर ग़म भी हसीं लगने लगता है।",
            "तुझसे मिलकर ज़िंदगी हसीन लगने लगी।",
            "तेरी मोहब्बत मेरा सबसे हसीन ख्वाब है।",
            "तू है तो सब कुछ है, तू नहीं तो कुछ भी नहीं।",
            "हर लम्हा तेरे साथ जीना चाहता हूँ।",
            "तू मेरी दुआओं का सबसे हसीन जवाब है।",
            "तेरा प्यार मेरी ज़िन्दगी का सबसे खूबसूरत हिस्सा है।",
            "तेरे बिना अधूरी सी लगती है ज़िंदगी।",
            "तेरी आँखों में ही बसी है मेरी दुनिया।",
            "तू मेरी धड़कनों में बसा है।",
            "तेरी हँसी में ही है मेरी जन्नत।",
            "मैं हर जनम में तुझे चाहता रहूँगा।",
            "तेरे साथ बिताया हर पल खास है।",
            "तू मेरी रूह में बसा है।",
            "मोहब्बत है तुझसे बेपनाह और बेवजह।",
            "तेरी आवाज़ सुनकर दिन बन जाता है।",
            "तेरे बिना ये दिल अधूरा है।",
            "मेरा दिल सिर्फ तेरा ही नाम लेता है।",
            "तेरे प्यार में ही मेरी दुनिया है।",
            "तू ही है जिससे दिल की हर बात कह सकूं।",
            "तेरे बिना सब अधूरा लगता है।",
            "तू मेरी हर सुबह की पहली सोच है।",
            "तेरे प्यार में खो जाना ही सुकून है।",
            "मुझे तुझसे बेइंतहा मोहब्बत है।",
            "तू मेरा आज है, कल है और हमेशा रहेगा।",
            "तेरे साथ ही मेरी हर कहानी शुरू होती है।",
            "तू ही है मेरी तन्हाईयों का सुकून।",
            "तेरे होने से ही मेरी दुनिया रोशन है।",
            "तेरा साथ ही मेरी जन्नत है।",
            "मैं सिर्फ तुझसे मोहब्बत करता हूँ।",
            "तेरा ख्याल हर लम्हा दिल में रहता है।",
            "तेरे बिना कुछ भी अच्छा नहीं लगता।",
            "तू मेरी आखिरी मोहब्बत है।",
            "तेरे चेहरे की रौनक ही मेरी राहत है।",
            "तेरे प्यार में ही तो मैंने खुद को पाया है।",
            "तेरा नाम मेरी हर धड़कन में है।",
            "तेरी बाहों में ही तो सुकून मिलता है।",
            "मेरा हर ख्वाब तुझसे जुड़ा है।",
            "तेरा हर लफ्ज़ मेरे दिल पर असर करता है।",
            "तेरी हर एक बात दिल को छू जाती है।",
            "तेरा साथ ही मेरी सबसे बड़ी दौलत है।",
            "तेरी यादें ही मेरी तन्हा रातों की साथी हैं।",
            "तेरे बिना अधूरी सी लगती है दुनिया।",
            "तू ही है जिससे जीने का मन करता है।",
            "तेरा इंतज़ार ही तो मेरी आदत बन गया है।",
            "तू है तो सब कुछ है।",
            "तेरा नाम मेरी ज़ुबां से कभी ना हटे।",
            "तेरे प्यार में ही मुझे ज़िन्दगी मिली है।",
            "তোমার হাসি আমার পৃথিবী সাজায়।",
            "তোমার চোখে আমি স্বপ্ন দেখি।",
            "তুমি ছাড়া জীবন অসম্পূর্ণ।",
            "তোমার প্রেমে আমি পূর্ণতা পেয়েছি।",
            "তোমার ভালোবাসাই আমার জীবনের আশ্রয়।",
            "প্রতি মুহূর্তে তোমার কথা ভাবি।",
            "তোমার ছোঁয়ায় হৃদয় কাঁপে।",
            "তুমি আমার হৃদয়ের রাজা/রানী।",
            "তোমার সাথে কাটানো প্রতিটি মুহূর্ত অমূল্য।",
            "তুমি না থাকলে কিছুই ভালো লাগে না।",
            "তোমার ভালোবাসা আমার সব থেকে বড় সম্পদ।",
            "তুমি আছো বলেই আজ আমি বাঁচছি।",
            "তোমার জন্যই এই জীবন এত সুন্দর।",
            "তোমার হাসিতে আমার মন ভরে যায়।",
            "তোমাকে ভালোবেসে আমি ধন্য।",
            "তুমি আমার জীবনের সবচেয়ে বড় উপহার।",
            "তোমার ভালোবাসা আমাকে বদলে দিয়েছে।",
            "তোমার চোখে আমি নিজের প্রতিচ্ছবি দেখি।",
            "তোমার স্পর্শে আমি স্বর্গ পাই।",
            "তুমি আমার হৃদয়ের প্রতিটি স্পন্দনে আছো।",
            "তুমি ছাড়া আমি কিছুই ভাবতে পারি না।",
            "তুমি আমার হৃদয়ের কবিতা।",
            "তোমার প্রেমে আমি ডুবে যেতে চাই।",
            "তোমার কন্ঠ আমার শান্তির স্থান।",
            "তোমার প্রতিটি কথা আমার মন ছুঁয়ে যায়।",
            "তোমার ভালোবাসাই আমার অস্তিত্ব।",
            "তুমি ছাড়া আমার সকাল শুরু হয় না।",
            "তোমার সান্নিধ্যে আমি নিজেকে খুঁজে পাই।",
            "তুমি আমার একমাত্র ভালোবাসা।",
            "তোমার হাসিই আমার প্রিয় গান।",
            "তোমার সাথে পথ চলা চাই সারাজীবন।",
            "তোমার স্মৃতি আমার প্রিয় সম্পদ।",
            "তোমার জন্যই আমি প্রতিদিন বাঁচতে শিখছি।",
            "তোমাকে ভালোবেসে আমি ধন্য হয়েছি।",
            "তোমার ভালোবাসা আমার প্রেরণা।",
            "তোমার সাথে থাকার ইচ্ছা চিরন্তন।",
            "তুমি ছাড়া এই পৃথিবী ফাঁকা মনে হয়।",
            "তোমার চোখে আমার স্বপ্ন লুকানো।",
            "তোমার প্রেমে আমার মন হারিয়েছে।",
            "তুমি আমার জীবনের ছায়া।",
            "তোমার কথা মনে হলেই হৃদয় কাঁপে।",
            "তোমার প্রেম আমার জীবনের আলো।",
            "তুমি আমার জীবনের একমাত্র চাওয়া।",
            "তোমার ভালোবাসা আমায় বাঁচায়।",
            "তোমার সাথেই আমি অনন্ত চাই।",
            "তোমার স্পর্শে হৃদয়ে জোয়ার আসে।",
            "তোমার নামেই শুরু ও শেষ।",
            "তুমি আমার ভালোবাসার শেষ অধ্যায়।",
            "তুমি না থাকলে এই জীবন অর্থহীন।"

        )),
        ShayriAppModel("Sad", listOf(
            "Tears are words the heart can't say.",
            "Some wounds never heal, they just stay silent.",
            "I smile to hide the pain inside.",
            "Missing you is a silent agony.",
            "Sometimes the person who broke you is the only one who can fix you.",
            "Pain taught me how to survive.",
            "Letting go is harder than holding on.",
            "I pretend to be okay, but I'm not.",
            "Silence speaks the loudest pain.",
            "I trusted you, and you broke me.",
            "Loneliness is the worst kind of pain.",
            "Every smile hides a tear.",
            "Love left me hollow.",
            "I lost myself loving you.",
            "You promised forever, but left too soon.",
            "Fake smiles, real pain.",
            "Hearts break silently.",
            "Love turned into sorrow.",
            "Pain is my only companion now.",
            "I miss the old me.",
            "I'm tired of being strong.",
            "Crying inside, laughing outside.",
            "Some goodbyes are forever.",
            "Hope hurts when it's false.",
            "I'm fading in the crowd.",
            "Tears are my only escape.",
            "You left, and took my soul.",
            "I wish I could forget you.",
            "Why does love hurt this much?",
            "The heart bleeds in silence.",
            "I still wait for your return.",
            "Emptiness surrounds me.",
            "I wish I never met you.",
            "Memories haunt me.",
            "I was better alone.",
            "Love betrayed me.",
            "Darkness is now my home.",
            "I’m not okay, just pretending.",
            "Even my shadow left me.",
            "I gave everything and lost myself.",
            "Your silence screams louder.",
            "My heart cries every night.",
            "You were my happiness, now my pain.",
            "Sadness is permanent now.",
            "No one understands the pain.",
            "I’m breaking slowly.",
            "It hurts to remember you.",
            "My soul aches for peace.",
            "Your memories are poison.",
            "Pain lives here, rent-free.",
            "आँखों में नींद नहीं, बस ख्वाब अधूरे हैं।",
            "वो हँसते हैं मुझसे जो दर्द नहीं जानते।",
            "तू मेरे साथ भी नहीं, और तुझ बिन भी नहीं।",
            "हम मुस्कुरा के ग़म छुपा लेते हैं।",
            "हर रिश्ता दर्द दे गया।",
            "दिल अब किसी से उम्मीद नहीं करता।",
            "सच तो ये है कि अब कोई फर्क नहीं पड़ता।",
            "तेरे जाने से कुछ नहीं बदला, बस जीने की वजह चली गई।",
            "खुश रहने की कोशिश में और टूट गए।",
            "वो ख्वाब अब सिर्फ आँखों में चुभते हैं।",
            "तेरे बिना सब अधूरा लगता है।",
            "कभी कभी खुद से भी नफ़रत हो जाती है।",
            "दिल अब बस धड़कता है, जीता नहीं।",
            "ज़िन्दगी से अब कोई शिकायत नहीं, सब कुछ तो खो दिया।",
            "हर रोज़ खुद को समझाते हैं, कि सब ठीक है।",
            "वो पल अब सिर्फ यादों में रह गए।",
            "दर्द तो अब आदत बन गई है।",
            "कोई था, जो कभी बहुत अपना था।",
            "अब तो अश्क भी थक चुके हैं।",
            "तेरी खामोशी ने बहुत कुछ कह दिया।",
            "वो यादें अब साँसें बन गई हैं।",
            "हम जी तो रहे हैं, पर मरते हुए।",
            "तेरे बाद किसी से दिल नहीं लगा।",
            "जो दिल में रहते हैं, वही सबसे ज्यादा दर्द देते हैं।",
            "दर्द जब हद से गुजर जाता है, तो इंसान हँसने लगता है।",
            "छोड़ दिया सब पर यकीन करना।",
            "तन्हाई अब सबसे अच्छी लगती है।",
            "हम तो बस खुद में ही सिमट गए।",
            "उसकी यादें अब भी रुला जाती हैं।",
            "जिसे चाहा, वही पराया हो गया।",
            "ज़िन्दगी अब बोझ सी लगती है।",
            "रोते हैं तो दिल हल्का होता है।",
            "ख्वाहिशें अब मिट चुकी हैं।",
            "अब किसी से कोई उम्मीद नहीं।",
            "तेरी यादें अब सुकून नहीं देतीं।",
            "जिसे दिल दिया, उसी ने तोड़ा।",
            "अब दिल नहीं करता किसी से बात करने का।",
            "कुछ दर्द ऐसे होते हैं जो कहे नहीं जाते।",
            "उसकी मुस्कान अब ज़हर लगती है।",
            "दिल अब टूटा ही रहेगा।",
            "हम भी किसी के बिना अधूरे हैं।",
            "तू भी क्या खूब बेवफा निकला।",
            "तेरे ख्याल ही अब जीने नहीं देते।",
            "हर दिन एक सजा सी लगती है।",
            "जिसे टूट कर चाहा, वो ही छोड़ गया।",
            "अब कुछ भी अच्छा नहीं लगता।",
            "जिसे अपना समझा, वो अजनबी निकला।",
            "बस अब खत्म हो जाना चाहता हूँ।",
            "अब जीने की तमन्ना नहीं रही।",
            "खुद को खो चुका हूँ कहीं।",
            "চোখের জলে সব কথা বলা যায় না।",
            "ভালোবাসা শুধু কষ্ট দেয়।",
            "তুমি ছিলে, এখন শুধুই স্মৃতি।",
            "মনের ভিতরটা ফাঁকা ফাঁকা লাগে।",
            "চেষ্টা করি হাসতে, কিন্তু পারি না।",
            "তুমি ছাড়া কিছুই ভালো লাগে না।",
            "হারিয়ে ফেলেছি নিজেকে।",
            "তুমি ভালো থেকো, আমি তো অভ্যস্ত কষ্টে।",
            "আমার কান্না এখন নীরব।",
            "ভালোবাসা মানেই ব্যথা।",
            "তোমার অভাবটা প্রতি মুহূর্তে টের পাই।",
            "মনে হয়, আমি আর আগের আমি নই।",
            "যে কাঁদে, সে সত্যি ভালোবাসে।",
            "ভালোবাসা পেলাম না, শুধু অপেক্ষা।",
            "ভেতরে ভেতরে আমি মরে গেছি।",
            "তুমি যেদিন চলে গেলে, জীবন থেমে গেছে।",
            "তোমার স্মৃতি গুলো পোড়ায় আমাকে।",
            "যার জন্য সব করলাম, সে কিছুই বুঝল না।",
            "ভাঙা মন নিয়ে বাঁচা খুব কঠিন।",
            "আমি তো শুধুই একা।",
            "ভালোবাসা আজ শুধুই গল্প।",
            "তোমার ফেলে যাওয়া প্রতিটি কথা এখন বিষ।",
            "আমি চেষ্টা করি ভুলতে, পারি না।",
            "তোমার অভিমানটাই শেষ করল সব।",
            "সবাই নিজের মতো ভালোবাসে।",
            "কান্না এখন অভ্যাস হয়ে গেছে।",
            "তুমি চাওনি বুঝতে, আমি কতটা ভেঙে গেছি।",
            "ভালোবাসা নয়, কষ্টটাই সত্যি।",
            "তুমি ছিলে বলেই আমি ছিলাম।",
            "স্মৃতি গুলো এখন গলার কাঁটা।",
            "তোমার প্রতি ভালোবাসা আজও অটুট।",
            "তুমি যদি ফিরে আসতে!",
            "ভালোবাসি আজও, কিন্তু তুমিও তো দূরে।",
            "সব হারিয়ে এখন নিঃস্ব।",
            "ভালোবাসায় আজ বিশ্বাস নেই।",
            "তুমি সুখ খুঁজলে, আমি শুধু তোমাকে।",
            "তোমার ছায়াটাও আজ অচেনা।",
            "মনে হয় জীবনটাই ভুল ছিল।",
            "আমি যে কষ্টে আছি, কেউ বোঝে না।",
            "ভালোবাসা শুধু একতরফা ছিল।",
            "সব কথা বলা যায় না, কিছু অনুভব করতে হয়।",
            "তুমি আমায় ভালোবাসো নি, আমি সেটা দেরিতে বুঝেছি।",
            "তোমার অভাবটাই সবচেয়ে বড় সত্যি।",
            "জীবন এখন শুধু বেঁচে থাকা।",
            "তুমি হারিয়ে গেলে, আমিও হারিয়ে গেলাম।",
            "চোখের জল এখন শব্দহীন ব্যথা।",
            "ভালোবাসার নামেই যত ছলনা।",
            "আমার হৃদয় আজও তোমার নামে লেখা।",
            "তোমার জন্য কষ্ট পেতেও ভালো লাগে।",
            "আমি ভালো নেই, কিন্তু কেউ জানে না।"
        )),
        ShayriAppModel("Friendship", listOf(
            "A true friend is a treasure for life.",
            "Friends are the family we choose.",
            "Good times and crazy friends make the best memories.",
            "Friendship is the purest form of love.",
            "With friends, even silence is fun.",
            "A friend in need is a friend indeed.",
            "Life is better with true friends.",
            "Friends make life worth living.",
            "Old friends are gold.",
            "True friends are never apart, maybe in distance but never in heart.",
            "Friends are the sunshine of life.",
            "Laughter is louder when friends are around.",
            "A friend’s hug heals a thousand pains.",
            "Real friends never leave your side.",
            "Friendship doesn’t need daily conversation, just a heart connection.",
            "In the garden of life, friendship is the sweetest flower.",
            "True friendship stands the test of time.",
            "Friends know your story, best friends help you write it.",
            "Friendship is built on trust, love, and countless memories.",
            "No road is long with good company.",
            "Friends are anchors in life’s storms.",
            "With friends, every moment is a celebration.",
            "Best friends are rare but real.",
            "Friendship grows with care, love, and loyalty.",
            "Good friends are hard to find, harder to leave, and impossible to forget.",
            "A friend’s support is life’s best gift.",
            "Friendship is the glue that binds hearts.",
            "True friendship needs no reason or season.",
            "Friends are like stars, you don't always see them but you know they're there.",
            "Friends understand you without words.",
            "Loyalty is the heartbeat of true friendship.",
            "Friendship doubles the joy and halves the sorrow.",
            "A single loyal friend is worth more than a thousand fake ones.",
            "Best friends bring out the best in us.",
            "True friends never judge, they accept you.",
            "Friends turn ordinary days into special memories.",
            "Friendship means laughing till your stomach hurts.",
            "Friendship is the golden thread in the fabric of life.",
            "A real friend walks in when the rest walk out.",
            "Friends are the melody of life.",
            "With friends, problems feel lighter.",
            "Friendship is the key to a happy heart.",
            "True friends are forever blessings.",
            "The best friendships are effortless.",
            "A friend’s silence says more than many words.",
            "Every moment with friends is a gift.",
            "Friendship is a promise kept in the heart.",
            "True friends grow together, not apart.",
            "Friends color your world with joy.",
            "Time may pass, but friendship stays eternal.",
            "दोस्ती हर रिश्ते से प्यारी होती है।",
            "सच्चा दोस्त वही है जो हर हाल में साथ दे।",
            "दोस्त वही जो मुश्किल में काम आए।",
            "दोस्ती में ना कोई दिन होता है, ना कोई वजह।",
            "जहाँ दोस्त होते हैं वहाँ मुस्कान खुद चलकर आती है।",
            "सच्चे दोस्त कभी दूर नहीं होते।",
            "दोस्ती ज़िन्दगी की सबसे बड़ी दौलत है।",
            "दोस्ती एक ऐसा रिश्ता है जो दिलों को जोड़ता है।",
            "जहाँ दोस्त हैं, वहाँ खुशी है।",
            "दोस्त वो होता है जो बिना कहे समझ जाए।",
            "दोस्ती के बिना ज़िन्दगी अधूरी है।",
            "दोस्तों की हँसी सबसे प्यारी लगती है।",
            "सच्ची दोस्ती वक्त नहीं, दिल देखती है।",
            "दोस्ती एक एहसास है, जो दिल से जुड़ा होता है।",
            "दोस्ती का कोई मोल नहीं होता।",
            "सच्चे दोस्त भगवान का आशीर्वाद होते हैं।",
            "दोस्ती वो रिश्ता है जिसमें शिकायत नहीं, सिर्फ अपनापन होता है।",
            "दोस्तों के बिना ज़िन्दगी फीकी लगती है।",
            "दोस्ती हर दर्द को मिठास में बदल देती है।",
            "दोस्त वो होते हैं जो आँसू भी पहचान लेते हैं।",
            "दोस्ती की मिसाल कोई नहीं।",
            "दोस्ती का रिश्ता बहुत खास होता है।",
            "सच्चा दोस्त वही जो हर हाल में साथ दे।",
            "दोस्ती में कोई शर्त नहीं होती।",
            "दोस्त मिलते हैं तक़दीर से।",
            "दोस्ती में अगर सच्चाई हो, तो रिश्ता कभी नहीं टूटता।",
            "दोस्त वो तोहफा है जो खुदा हर किसी को नहीं देता।",
            "एक सच्चा दोस्त हज़ार रिश्तों के बराबर होता है।",
            "दोस्ती हर ग़म को ख़ुशी बना देती है।",
            "दोस्ती दिलों को जोड़ने वाला पुल है।",
            "दोस्त वो होता है जो बिना वजह भी याद करता है।",
            "हर दोस्त खास होता है।",
            "दोस्ती ज़िन्दगी का सबसे सुंदर तोहफा है।",
            "दोस्तों के साथ बिताया हर पल खास होता है।",
            "सच्चे दोस्त बिना बोले भी समझ जाते हैं।",
            "दोस्ती समय नहीं, भावनाओं से जुड़ती है।",
            "दोस्ती में मज़ा है, जीवन में रंग है।",
            "सच्ची दोस्ती वक्त नहीं देखती।",
            "दोस्ती का रिश्ता दिल से होता है।",
            "एक सच्चा दोस्त दुख में संबल बनता है।",
            "दोस्ती की खुशबू दूर तक जाती है।",
            "सच्ची दोस्ती उम्र भर निभती है।",
            "दोस्ती शब्दों से नहीं, दिल से होती है।",
            "दोस्ती ज़िन्दगी को आसान बना देती है।",
            "हर मुस्कान के पीछे एक दोस्त होता है।",
            "दोस्ती वो रिश्ता है जो बिना खून के भी खून से गाढ़ा होता है।",
            "दोस्तों की बातें कभी पुरानी नहीं होतीं।",
            "जहाँ दोस्त हैं, वहाँ फिक्र नहीं होती।",
            "दोस्ती निभाना हर किसी के बस की बात नहीं।",
            "सच्चा दोस्त वही है जो पीछे नहीं हटता।",
            "বন্ধুত্ব হলো হৃদয়ের এক নিঃশর্ত সম্পর্ক।",
            "সত্যিকারের বন্ধু সবসময় পাশে থাকে।",
            "বন্ধুত্বে কখনো শর্ত থাকে না।",
            "বন্ধুর হাসি মন ভালো করে দেয়।",
            "বন্ধু মানেই জীবনের আলো।",
            "যেখানে বন্ধু আছে, সেখানে দুঃখও কম লাগে।",
            "বন্ধুদের সঙ্গে সময় উড়ে যায়।",
            "স্মৃতিগুলো সুন্দর হয় বন্ধুদের জন্য।",
            "বন্ধু মানেই নির্ভরতা।",
            "বন্ধু ছাড়া জীবন অসম্পূর্ণ।",
            "একজন বন্ধু হাজার আত্মীয়ের সমান।",
            "বন্ধুত্বে না আছে জাত, না আছে ধর্ম।",
            "বন্ধু হৃদয়ের অমূল্য রত্ন।",
            "বন্ধুত্ব হলো আত্মার বন্ধন।",
            "ভালো বন্ধু জীবনের আশীর্বাদ।",
            "বন্ধুরা জীবনের সবচেয়ে বড় উপহার।",
            "বন্ধু মানেই বিশ্বাস।",
            "বন্ধুর সঙ্গে কাটানো সময় অমূল্য।",
            "একজন বন্ধু সব কিছু সহজ করে দেয়।",
            "বন্ধুদের সঙ্গে দুঃখও আনন্দ মনে হয়।",
            "ভালো বন্ধু জীবনের পথ প্রদর্শক।",
            "বন্ধু ছাড়া জীবনের কোনো মানে নেই।",
            "যে বন্ধু কাঁধে হাত রাখে, সে জীবনের সাথী।",
            "স্মৃতি আর বন্ধুত্ব চিরকাল বেঁচে থাকে।",
            "বন্ধুরা জীবনের সবচেয়ে মিষ্টি অংশ।",
            "যেখানে বন্ধু আছে, সেখানে ভয় নেই।",
            "বন্ধুত্ব সময় চায় না, ভালোবাসা চায়।",
            "সত্যিকারের বন্ধু দূরেও থাকলে কাছের হয়।",
            "বন্ধু মানেই মান-অভিমান, তবুও ভালোবাসা।",
            "বন্ধুদের সঙ্গে সবকিছু ভাগ করে নেওয়া যায়।",
            "বন্ধুত্বের আসল মানে হলো অনুভব।",
            "একজন বন্ধু মানেই সুখের সঙ্গী।",
            "বন্ধু ছাড়া হেসে নেওয়া কঠিন।",
            "সত্যিকারের বন্ধুত্ব দূরত্ব মানে না।",
            "বন্ধুদের ভালোবাসা অমূল্য।",
            "বন্ধুর স্পর্শেও শান্তি পাওয়া যায়।",
            "বন্ধুত্ব মানেই রঙিন জীবন।",
            "বন্ধুরা জীবনের ছায়া।",
            "সুখে দুঃখে পাশে থাকে যে, সে-ই সত্যিকারের বন্ধু।",
            "বন্ধুত্ব শব্দে নয়, মনে থাকে।",
            "স্মৃতির খাতায় বন্ধুদের নাম লেখা থাকে।",
            "বন্ধুরা জীবনকে অর্থ দেয়।",
            "বন্ধুত্ব চুপচাপ থেকেও গভীর হয়।",
            "বন্ধু মানেই নিরাপদ আশ্রয়।",
            "বন্ধুর সান্নিধ্য জীবনকে আনন্দ দেয়।",
            "বন্ধু ছাড়া ভালোবাসার মানে হয় না।",
            "বন্ধুরা জীবনের গল্পে সবচেয়ে সুন্দর চরিত্র।",
            "সত্যিকারের বন্ধুত্ব সময়ের সঙ্গে আরও মজবুত হয়।",
            "বন্ধু মানেই কখনো না ভুলে যাওয়া সম্পর্ক।"
            // ... continue to 50
        )),

        ShayriAppModel("Motivation", listOf(
            "Rise above the storm to find the sunshine.",
            "Success begins with self-belief.",
            "Hard times teach the best lessons.",
            "Don’t wait for opportunity. Create it.",
            "The pain you feel today is strength tomorrow.",
            "Failure is not defeat, it's a lesson.",
            "Dream big, work hard, stay focused.",
            "Winners never quit, and quitters never win.",
            "Believe you can, and you're halfway there.",
            "Every sunset brings the promise of a new dawn.",
            "Push yourself, no one else will do it for you.",
            "Make your life a masterpiece.",
            "Your only limit is your mind.",
            "Turn the pain into power.",
            "Don’t be afraid to start over.",
            "You’re stronger than you think.",
            "Never let fear decide your future.",
            "Success tastes better after struggle.",
            "You were born to shine.",
            "Let your hustle make the noise.",
            "Great things never come from comfort zones.",
            "One day, all the hard work will pay off.",
            "Every small step counts.",
            "Your journey is your power.",
            "Keep going, you're closer than you think.",
            "Doubt kills more dreams than failure.",
            "Wake up with determination, sleep with satisfaction.",
            "Dream it. Do it.",
            "Never give up on your passion.",
            "Let your scars become your strength.",
            "Patience and persistence conquer all.",
            "Be a warrior, not a worrier.",
            "Stars shine brightest in darkness.",
            "You don’t find willpower, you create it.",
            "Fall seven times, rise eight.",
            "Make your struggle your story.",
            "Impossible is just an opinion.",
            "Choose courage over comfort.",
            "One dream, one goal, one life – make it count.",
            "Chase the vision, not the money.",
            "Success loves the brave.",
            "Keep your focus, and success will follow.",
            "Live with purpose, act with passion.",
            "The best is yet to come.",
            "Build yourself, break limits.",
            "Don’t stop until you're proud.",
            "You are your only competition.",
            "Take risks, grow stronger.",
            "Your grind will be your glory.",
            "Let your dreams be louder than your fears.",
            "দৃষ্টিভঙ্গি ভালো হলে জীবনও সুন্দর হয়।",
            "जो हार मान लेता है, वो जीत नहीं पाता।",
            "सपने उन्हीं के पूरे होते हैं जो मेहनत करते हैं।",
            "खुद पर विश्वास रखो, हर राह आसान लगेगी।",
            "जहां चाह, वहां राह।",
            "मुश्किलें ही इंसान को मजबूत बनाती हैं।",
            "सफलता मेहनत की मांग करती है।",
            "गिरकर संभलना ही असली जीत है।",
            "खुद को बदलो, दुनिया अपने आप बदलेगी।",
            "जो समय को पहचानता है, वही सफल होता है।",
            "हार में भी जीत की उम्मीद रखो।",
            "हर दिन एक नया मौका है।",
            "हिम्मत करने वालों की कभी हार नहीं होती।",
            "जो ठान लिया, वो कर दिखाओ।",
            "कभी हार मत मानो, कहानी अभी बाकी है।",
            "जो मेहनत करता है, वही चमकता है।",
            "अपनी काबिलियत पर यकीन रखो।",
            "जो डर गया, वो मर गया।",
            "जोश से नहीं, होश से आगे बढ़ो।",
            "जिनके इरादे मजबूत होते हैं, रास्ते खुद बन जाते हैं।",
            "हर सुबह एक नई शुरुआत है।",
            "सपनों को हकीकत में बदलो।",
            "मंज़िल उन्हीं को मिलती है जो चलते हैं।",
            "कभी रुकना नहीं, चाहे हालात जैसे भी हों।",
            "आज की मेहनत ही कल की पहचान बनेगी।",
            "तू चल, मैं साथ हूँ – तेरी मेहनत तेरी ताकत है।",
            "हर दर्द के पीछे एक सीख छिपी होती है।",
            "मंजिलें उन्हें मिलती हैं जो मेहनत पर यकीन रखते हैं।",
            "सोच को बदलो, सितारे खुद बदल जाएंगे।",
            "हर असफलता एक नई सीख होती है।",
            "कभी हार मत मानो, चमत्कार समय लेता है।",
            "अपना लक्ष्य बड़ा रखो, डर अपने आप छोटा हो जाएगा।",
            "तू मेहनत कर, किस्मत झुक जाएगी।",
            "जज़्बा अगर सच्चा हो तो रास्ते भी झुकते हैं।",
            "ताकत अपने अंदर ढूंढो।",
            "तू अकेला नहीं, तेरी मेहनत तेरे साथ है।",
            "खुद पर भरोसा रखो, यही जीत की पहली सीढ़ी है।",
            "कभी खुद को कमजोर मत समझो।",
            "हर सपना पूरा हो सकता है अगर हिम्मत हो।",
            "रास्ता चाहे कितना भी मुश्किल हो, मंज़िल ज़रूर मिलेगी।",
            "अपने आप से होड़ लगाओ।",
            "तू खुद की पहचान बन।",
            "जो खुद से लड़ता है, वही जीतता है।",
            "तू खुद एक प्रेरणा बन जा।",
            "अभी नहीं तो कभी नहीं।",
            "हार एक सीख है, मंज़िल नहीं।",
            "तू खुद को साबित कर।",
            "कोशिश करने वालों की कभी हार नहीं होती।",
            "तेरे इरादे अगर सच्चे हैं, तो मंज़िल दूर नहीं।",
            "खुद पर जीत ही असली जीत है।",
            "हिम्मत से बढ़कर कोई हथियार नहीं।",
            "যারা স্বপ্ন দেখে, তারাই ইতিহাস গড়ে।",
            "সফলতা আসে কঠোর পরিশ্রমের ফলে।",
            "নিজের উপর বিশ্বাস রাখো, কিছুই অসম্ভব নয়।",
            "লক্ষ্য ঠিক থাকলে পথ নিজেই তৈরি হয়।",
            "ব্যর্থতা মানেই নতুন শুরু।",
            "চেষ্টা কখনো বৃথা যায় না।",
            "যারা হার মানে না, তারাই জয়ী হয়।",
            "ভয় নয়, সাহস জীবন বদলে দেয়।",
            "আজকের কষ্ট আগামী দিনের সাফল্য।",
            "প্রতিদিন একটি নতুন সুযোগ।",
            "স্বপ্ন বড় হওয়া উচিত, কারণ সুযোগ সীমিত।",
            "চেষ্টা করো, ফল নিশ্চয় আসবে।",
            "যত বড় বাধা, তত বড় বিজয়।",
            "হার মানার আগে চেষ্টা করো।",
            "নিজের পথ নিজেই তৈরি করো।",
            "অবিশ্বাস নয়, আত্মবিশ্বাসেই শক্তি।",
            "আলো খুঁজে পেতে হলে অন্ধকার পেরোতে হয়।",
            "নিজেকে চেনো, জয় তোমার হবে।",
            "জীবন মানে থেমে না যাওয়া।",
            "আজ শুরু করো, কাল দেরি হয়ে যাবে।",
            "নিজের লক্ষ্য থেকে চোখ সরিও না।",
            "পরিশ্রম কখনো ব্যর্থ হয় না।",
            "সমস্যা নয়, সমাধান খুঁজো।",
            "নিজের উপর আস্থা রাখো, সাফল্য আসবেই।",
            "চেষ্টা না করলে কিছুই পাওয়া যায় না।",
            "মনের জোরই আসল শক্তি।",
            "জয় তাদেরই হয়, যারা সবকিছু সহ্য করতে জানে।",
            "অভিনব ভাবনাই সাফল্যের চাবিকাঠি।",
            "শিখতে শিখতেই সফল হও।",
            "স্বপ্ন পূরণের জন্য সাহস লাগে।",
            "নিজেকে হারালে সব কিছু হারাবে।",
            "যতবার পড়বে, ততবার উঠো।",
            "শুধু স্বপ্ন নয়, কাজেও লাগাও।",
            "তুমি পারো, শুধু চেষ্টা করো।",
            "হেরে যাওয়া মানে শেষ নয়।",
            "সফলতা ধৈর্যের ফল।",
            "ভাল কিছু পেতে হলে কষ্ট পেতেই হবে।",
            "তুমি তৈরি হতে থাকো, সুযোগ আসবেই।",
            "জীবনে চলা থামালে, সব থেমে যায়।",
            "স্বপ্ন পূরণ করতে গেলে সাহস লাগে।",
            "তোমার প্রতিযোগী তুমি নিজেই।",
            "জয় করতে চাইলে বিশ্বাস রাখতে হবে।",
            "নিজেকে বদলাও, পৃথিবী আপনাআপনি বদলাবে।",
            "শুরু করো, দেখা যাবে গন্তব্যও কাছে।",
            "যে হার মানে না, সে একদিন জেতে।",
            "যত কঠিন হোক, লড়াই চালিয়ে যাও।",
            "নিজের গন্তব্য তুমি নিজেই নির্ধারণ করো।",
            "সাহসই আসল শক্তি।",
            "স্বপ্ন পূরণের যুদ্ধে লড়াই করতে হয়।",
            "যতবার পড়ো, ততবার উঠে দাঁড়াও।"
            // ... continue to 50
        )),
        ShayriAppModel("Life", listOf(
            "Life is a journey, not a destination.",
            "Learn to smile through the pain.",
            "Every moment is a new beginning.",
            "Life teaches more than any book.",
            "Change is the only constant in life.",
            "In the end, we only regret the chances we didn't take.",
            "Life isn’t perfect, but it’s beautiful.",
            "Time heals everything, be patient.",
            "Live the moment, not the memories.",
            "Happiness comes from within.",
            "Some chapters must close for better ones to begin.",
            "Everything happens for a reason.",
            "Let go of what you can’t control.",
            "Real strength is staying kind in a cruel world.",
            "Life is short, make it meaningful.",
            "Be thankful for every breath you take.",
            "Sometimes silence speaks the loudest truth.",
            "Life moves on, so must you.",
            "Don’t just exist, live fully.",
            "Your life, your rules.",
            "Every fall teaches a new lesson.",
            "The beauty of life lies in its imperfection.",
            "Don't fear change, embrace it.",
            "Life rewards the brave.",
            "Peace is the real success.",
            "A meaningful life begins with self-love.",
            "You grow through what you go through.",
            "Live in the present, not the past.",
            "Joy is found in simple things.",
            "Life is too short for regrets.",
            "Make memories, not excuses.",
            "Choose love, not hate.",
            "Life blooms when you believe in yourself.",
            "Be real, be kind, be you.",
            "Let life surprise you.",
            "Wake up with purpose, sleep with pride.",
            "Pain shapes you, not destroys you.",
            "Be a light in someone’s darkness.",
            "Sometimes losing is winning in disguise.",
            "Life gets better with hope.",
            "Kindness never goes unnoticed.",
            "Live without pretending, love without depending.",
            "In life, balance is the key.",
            "Life is a reflection of your mindset.",
            "Accept what is, let go of what was.",
            "Life is a canvas, paint it with love.",
            "Moments matter more than material.",
            "Every breath is a second chance.",
            "Live like there's no tomorrow.",
            "Life whispers wisdom in silence.",
            "ज़िन्दगी एक किताब की तरह है, हर पन्ना कुछ सिखाता है।",
            "जो चला गया, उसे सोच कर वक़्त मत गंवाओ।",
            "ज़िन्दगी में सबसे बड़ा धन सुकून है।",
            "खुश रहो, क्योंकि यही ज़िन्दगी है।",
            "हर सुबह एक नया मौका लाती है।",
            "जो है, उसी में खुशी ढूंढो।",
            "ज़िन्दगी छोटी है, मुस्कुरा कर जियो।",
            "जो जैसा है, उसे वैसे ही अपनाओ।",
            "बीते वक्त को सोच कर मत रोओ।",
            "ज़िन्दगी एक सफर है, मज़े से जियो।",
            "ग़म और खुशी दोनों आते-जाते हैं।",
            "सपनों को जियो, डर को नहीं।",
            "जो भी करो दिल से करो।",
            "ज़िन्दगी को समझने में ही ज़िन्दगी बीत जाती है।",
            "जहाँ सुकून हो, वही रहो।",
            "अपने आप से प्यार करना सीखो।",
            "खुद की पहचान सबसे जरूरी है।",
            "ज़िन्दगी हर दिन एक नई सीख देती है।",
            "हर मोड़ पर कुछ नया मिलता है।",
            "जो खो गया, वो सीख बन गया।",
            "ज़िन्दगी जियो, गिनो मत।",
            "हर किसी से कुछ सीखो।",
            "खुशियाँ बांटो, बढ़ेंगी।",
            "शिकायतों से दूर रहो।",
            "जो मिला है, उसका शुक्र करो।",
            "अपने हालात खुद बदलो।",
            "जो बीत गया, वो सिखा गया।",
            "ज़िन्दगी ठहरती नहीं, चलती रहती है।",
            "हर दिल अपनी कहानी है।",
            "जो होना है, होकर रहेगा।",
            "ज़िन्दगी जैसी है, वैसी ही सुंदर है।",
            "बदलाव ज़रूरी है ज़िन्दगी में।",
            "ज़िन्दगी सब्र और उम्मीद से चलती है।",
            "अपने दिल की सुनो।",
            "जहाँ दिल खुश हो, वही रहो।",
            "हर रिश्ते में सच्चाई होनी चाहिए।",
            "जियो ऐसे कि किसी को शिकायत न हो।",
            "मुश्किलें ही असली ज़िन्दगी हैं।",
            "जो खोया, उसका ग़म मत करो।",
            "अपने आप में खुश रहना सीखो।",
            "ज़िन्दगी को हल्के में मत लो।",
            "हर दिन एक नई शुरुआत है।",
            "खुश रहने का सबसे अच्छा तरीका है – खुद से प्यार करना।",
            "ज़िन्दगी उम्मीदों से चलती है।",
            "हर दुख के पीछे कोई सीख छिपी है।",
            "ज़िन्दगी में मुस्कान जरूरी है।",
            "अपने समय की कद्र करो।",
            "जो है, उसी में खुश रहना सीखो।",
            "ज़िन्दगी को जीओ, डर से नहीं।",
            "हर पल को आख़िरी समझ कर जियो।",
            "জীবন একটা পথ, চলতে শেখায়।",
            "ভুল থেকে শেখাটাই আসল জীবন।",
            "যা আছে, তাতেই খুশি থাকো।",
            "হাসি দিয়ে শুরু করো প্রতিটা দিন।",
            "জীবন প্রতিটা মুহূর্তের সম্মান করতে শেখায়।",
            "ভালোবাসা, শ্রদ্ধা আর শান্তিই জীবন।",
            "অতীত ভুলে, বর্তমানকে জড়িয়ে ধরো।",
            "জীবন প্রতিদিন এক নতুন সুযোগ।",
            "যা গেছে, তা শিক্ষা হয়ে ফিরে আসুক।",
            "চেষ্টা করো, জীবনের মানে খুঁজে পাবে।",
            "নিয়মিত বদলানোই জীবন।",
            "নিজেকে ভালোবাসো, জীবন আপনাকে ভালোবাসবে।",
            "জীবন একটাই, ভালোভাবে বাঁচো।",
            "সব সময় কিছু শেখায় জীবন।",
            "সুখ-দুঃখ মিলিয়েই তো জীবন।",
            "মনের শান্তিই জীবনের শান্তি।",
            "চুপচাপ থেকেও জীবন অনেক বলে।",
            "জীবন একটা বই, প্রতিটি পৃষ্ঠা শেখায় কিছু।",
            "নিজেকে হারালে, জীবন হারায়।",
            "ভুল করে শিখে যাও, থেমো না।",
            "যা করো, মনের থেকে করো।",
            "সময়কে ব্যবহার করতে শিখো।",
            "আজকের কাজ কালকের ভবিষ্যৎ।",
            "নিজেকে বোঝাই জীবনের সবচেয়ে বড় শিক্ষা।",
            "জীবন হাসির মাঝেই সুন্দর।",
            "মনে শান্তি থাকলে জীবনও সুন্দর।",
            "যা পেয়েছো, তার মূল্য দাও।",
            "জীবনের প্রতি কৃতজ্ঞ হও।",
            "মনে রাখো – জীবন প্রতিদিন নতুন সুযোগ।",
            "হার-জিত নয়, শেখাটাই আসল।",
            "জীবনের প্রতিটা মুহূর্ত মূল্যবান।",
            "বাইরের নয়, ভিতরের সুখই আসল।",
            "নিজের মত করে জীবন গড়ে তোলো।",
            "মনের চোখে দেখো জীবনকে।",
            "ভালোর জন্য অপেক্ষা করো।",
            "জীবনে সহজ কিছুই নেই, তবু সুন্দর।",
            "তোমার জীবন, তোমার নিয়ম।",
            "যতক্ষণ শ্বাস, ততক্ষণ আশ।",
            "জীবনে বিশ্বাস রাখো।",
            "শান্ত জীবনই সফল জীবন।",
            "হাসো, কারণ জীবন সুন্দর।",
            "স্মৃতি নয়, বর্তমানটাই জীবন।",
            "বাঁচো এমনভাবে, যেন প্রতিটি দিন শেষ দিন।",
            "চেষ্টা করে যাও, ফল আসবেই।",
            "জীবন নিজেই এক উপহার।",
            "ভালোবাসা ছাড়া জীবন অসম্পূর্ণ।",
            "কঠিন সময়ই জীবনের আসল শিক্ষক।",
            "ভুলে যাও না, জীবন চলছে।",
            "আজকের প্রতিটি সেকেন্ড মূল্যবান।",
            "নিজের গল্প নিজেই লিখো।"

            // ... continue to 50
        ))
    )
}